### ISSUE TITLE
Configurable setting names

### ISSUE THREAD

**Issue by TadiklCZE** [dieterblancke/BungeeUtilisalsX#155]
Make friend setting names configurable.

**Comment by dieterblancke** [comment]
This should already be supported, you can add "friends.settings.type.server_switch" into your language file:

```
friends:
  settings:
    type:
      server_switch: 'serverswitch'
      friend_broadcast: 'friendbroadcast'
      ...
```
