### ISSUE TITLE
[FEATURE] Server-specific custom commands

### ISSUE THREAD

**Issue by xenforq** [dieterblancke/BungeeUtilisalsX#41]
Give us the ability to create server-specific custom commands, adjustable with server groups.

**Comment by dieterblancke** [comment]
This should be added in this build: https://github.com/dieterblancke/BungeeUtilisalsX/actions/runs/89526590

Please confirms if this works as intended or not, by default "ALL" is the server.

Usage:
```yaml
  - name: 'whoami'
    server: 'Lobbies'
    messages:
      - text: '&eYour name is &b{user}&e.'
```
