### ISSUE TITLE
[BUG] Helpop suggest command

### ISSUE THREAD

**Issue by ArcadeFighter** [dieterblancke/BungeeUtilisalsX#42]
**Describe the bug**
Issue with Helpop interaction option (suggest command in chat)

**To Reproduce**
1. Go to languages/en_US.yml
2. Scroll down to Helpop
3. Edit broadcast to:
```
  helpop:
    broadcast:
      text: '&7(&3&lHELPOP&7) &b{user} &7» &f{message}'
      click:
        type: 'SUGGEST_COMMAND'
        action: '/helpop reply {user} '
```

**Expected behavior**
When some player send an helpop message, staff can click on that message and it will suggest command in chat.

**Screenshots**
https://media.discordapp.net/attachments/366937609848619009/704332822219063367/unknown.png

**Versions:**
 - BungeeCord: __WaterfallMC #340 (Aegis)__
 - Client: __Paper 1.12.2__

**BungeeUtilisals Dump**
https://paste.dbsoftwares.eu/awunaguheb.dump
