### ISSUE TITLE
[FEATURE] Improved chat (antiswear) filter.

### ISSUE THREAD

**Issue by MoonSoD** [dieterblancke/BungeeUtilisalsX#56]
**Is your feature request related to a problem? Please describe.**
Well, I hate the lack of features and configurability of the chat filter.

**Describe the solution you'd like**
So, first of all I would like to also block regex expressions in addition to normal words. Create
the expressions in kinds of groups, where you could also whitelist certain expressions/words. Every group should have a specific ID in the config which could be used as an identifier of false positives of the configured swear filter.

For example:
 ```yaml
duck: #ID of the filter group
    whitelist:  #messages to bypass this certain filter
      - 'ducker'
    expression: '^(du+ck.+)'
```

This also creates a possibility to create a more detailed staff notification with the ID  of the triggered filter group.
e.g.: 
```Swear | ID - playerName > message```
```Swear | duck - MoonSoD > ducking```
